### ISSUE TITLE
dataset sample

### ISSUE THREAD

**Issue by taoranyi** [maximeraafat/humbi_textured_meshes#1]
Humbi dataset website cannot be registered now. Can you provide dataset sample? Thanks.

**Comment by maximeraafat** [comment]
Hi, I am sorry to hear you are experiencing issues with the HUMBI dataset. Everything however seems to work fine on my side, I am still able to download the data and registering seems possible as well. To register, visit the [HUMBI website](https://humbi-data.net), click on *Log In* in the top right, and then on *Register* in the bottom right of the log in window. If you encounter any issues, you can also visit the registration page directly by following [this](http://humbi-data.net/05-new-user-register/) link.

For further support with access to the data, please contact the dataset authors right away, as they kindly request any registered user to not share the data with any third parties.

Cheers,
Maxime

**Comment by taoranyi** [comment]
Thank you very much for your patient reply. I will try to contact the dataset authors.
